config/routes.rb
Rails.application.routes.draw do
  # get 'games/create'
  # get 'games/edit'
  # get 'games/update'
  # get 'games/show'
   # get 'pages/home'
  resources :games
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pages/blog'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  QUESTIONS =[
  	"A t-il les yeux clairs ?",
  	"Est-ce un homme?",
  	"Est-il vegan ?",
  	"Es tu originaire d'aquitaine ?"
  ]


  def create
  	@game = Game.create
  	redirect_to edit_game_path(@game["id"], question_id: 0), method: :get
  end

  def edit
  	@question = QUESTIONS[params["question_id"].to_i]
  end

  def update
  	question_id = params["question_id"].to_i + 1
	@game = Game.find(params["id"])
	@game["answers"] << params["answer"]
	@game.save
	if question_id > 3
		redirect_to game_path(@game["id"]), method: :get
	else
		redirect_to edit_game_path(@game["id"], question_id: question_id), method: :get
	end
  end

  def show
  	@game = Game.find(params["id"])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def blog
article1 = {
	"title" => "Mon 1er article",
	"content" => "salut salut salut salut",
} 

article2 = {
	"title" => "Mon 2ème article",
	"content" => "cou cou cou cou couc ot",
}

article3 = {
	"title" => "Mon 3ème article",
	"content" => "hola hola hola ",
}

@articles = [article1, article2, article3]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/games/create.html.erb
<!-- <h1>Games#create</h1>
 -->

app/views/games/edit.html.erb
<h1><%= @question %></h1>

<p class="center">
<%= link_to "Oui", game_path(params["id"], answer: "yes", question_id: params["question_id"]), method: :patch, class: "btn btn-success"  %>
<%= link_to "Non", game_path(params["id"], answer: "no", question_id: params["question_id"]), method: :patch, class: "btn btn-danger"  %>
</p>

<!-- <%= link_to( "Question suivante", game_path(1), method: :patch, class: "btn btn-primary" ) %> -->

app/views/games/show.html.erb
  <div class="row">
    <div class="col-md-6">
      <div class="links">




<h1>Et voici vos résultats !</h1>

<ul>
<% @game["answers"].each do |answer| %>

<li> Ma réponse est <%= answer %> </li>


<% end%>
</ul>




      </div>
    </div>
    <div class="col-md-6">
      <img src="https://image.noelshack.com/fichiers/2019/12/4/1553189978-arturoburger.png?fbclid=IwAR3Afg3HOU4wEY67YxyrVNYRhaEYgwZh0DfwG0znOhdvvnXNgwt08_ZrFkI" alt="", class="avatar">
    </div>
  </div>

app/views/games/update.html.erb
<!-- <h1>Games#update</h1> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Akinator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/blog.html.erb
<h1> mon 1er blog </h1>

<p> blablablablablablalbalbalbalblalablabballalablablablabla</p>




<% @articles.each do |article|%>

<div class="article">
	<h2><%= article["title"]%></h2>
	<p><%=	article["content"]%></p>
</div>

<% end %>

app/views/pages/home.html.erb
<div class="container">



	<div class="row">
		<div class="col-md-6">
			<div class="links">

<br />

  <h1>Bienvenue sur Akinator !</h1>
<br />

      <p> Clique sur commencer le jeu !</p>
<br />
<br />
	<%= link_to "Commencer le jeu !", games_path, method: :post, class: "btn btn-primary" %>
<br />

			</div>
		</div>
		<div class="col-md-6">
      <br />
			<img src="https://image.noelshack.com/fichiers/2019/12/4/1553189978-arturoburger.png?fbclid=IwAR3Afg3HOU4wEY67YxyrVNYRhaEYgwZh0DfwG0znOhdvvnXNgwt08_ZrFkI" alt="", class="avatar">
		</div>
	</div>






</div>